name: flexible_toast 
description: A customizable Flutter notification library to display temporary messages.
version: 0.0.1 
homepage: https://github.com/emrhnzngn/flexible_toast 
repository: https://github.com/emrhnzngn/flexible_toast
issue_tracker: https://github.com/emrhnzngn/flexible_toast/issues
environment:
  sdk: '>=3.8.1' 
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0